### ISSUE TITLE
Nagios [Epic Task 1]: Install & Configure Nagios Server Core Application From Ansible

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2609]
As part of issue #2445 , some code is required to create and configure a new Nagios Core monitoring server, the following sub tasks are involved :-

*   [x] Create ansible playbook to install Nagios Server Core on Ubuntu 22.04 via Ansible
*   [x] Install bespoke tooling for Nagios server
    *   [x] nagios\_slack.pl - Perl Script To Send Notification To Slack
    *   [x] nagios\_graph - Nagios Plugin
    *   [x] pnp4nagios - Nagios Graphing Tool
*   [x] Manage User Configuration / Backup / Restore / Automate ? ( cgi.cfg / htpasswd.users )
    *   [x] Default Nagios Admin User Created
*   [x] Update server related global config files ( resource.cfg )
*   [x] Update server related global config files ( nagios.cfg )
*   [x] Create commands.cfg file from source.
    *   [x] Add Nagios/Slack Notification Command
*    [x]  Create Monitoring Configuration For Nagios Server
*   [x] Test Playbook On VM

Follow On Tasks:

1.  Determine How To Manage Users On New Nagios
2.  Nagios backup/restore
3.  Configure Security ( Certificates / SSL etc )

**Comment by steelhead31** [comment]
@sxa could you assign this to me please ?

**Comment by sxa** [comment]
NOTE: This is awaiting the approve and merge of https://githuhttps://github.com/adoptium/infrastructure/pull/2638

**Comment by sxa** [comment]
Above PR is merged so I'm closing this
