### ISSUE TITLE
Epic: Automate docker static system with Ansible and AWX

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3368]
Turning https://github.com/adoptium/infrastructure/issues/3306 into an epic.

What I would like to accomplish in this epic is to take our Docker Static setup and 'Ansibilise' it. The final product should be a system of playbooks and scripts which allow static container deployment via AWX or command line. 

We have https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml, but it is monolithic. I want to create something more modular, in which a user can choose which containers to deploy, which to remove, as well as an update to date inventory file containing a list of running containers.

Objectives, not necessarily in order:
- [x] #3370
- [x] Create job in AWX to deploy containers onto dockerhost machines (part of https://github.com/adoptium/infrastructure/issues/3370)
- [x] #3506
- [x] #3415
   - with port numbers
   - with jenkins node link
   -  necessary information such as architecture, OS, etc
- [ ] Create templates for dockerfiles, removing the need to have a different file for each new release of OS
- [ ] #3507
- [x] Documentation (should be done along the way)

**Comment by sxa** [comment]
OK - testing this on another aarch64 box using [k3s](https://docs.k3s.io/quick-start). Noting that by default it doesn't work as non-root because exporting `KUBECONFIG` to be `/etc/rancher/k3s/k3s.yaml` is something that is not-world readable and gets reset on each restart. Also: 
-  A simple `make deploy` doesn't work because the images being pulled (`quay.io/ansible/awx-operator:x.y.z`) appear to be x64 only, but they'll work under qemu emulation (Not ideal for production
- Version 2.11.0 appears not to work - 2.10.0 deploys ok
- `kubectl logs` was close to useless (but pointed me at the arch mismatch issue) `kubectl describe` is your friend for better status logs until you start the actual AWX deploy when `kubectl logs -f` is useful
- 
I still need to figure out how to make `/Vendor_Files` into the appropriate container

**Comment by Haroon-Khel** [comment]
Im going to close this epic. The 2 remaining issues can be worked on in later issues. The main objectives of this epic have been met
