### ISSUE TITLE
EPIC: Jenkins maintenance

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3380]
Creating this as an umbrella to tie all the jenkins activities together. For example:

- [ ] LTS patch updates [#lts](https://github.com/adoptium/infrastructure/issues/3376)
- [ ] [Clearing up warnings in the system log](https://github.com/adoptium/infrastructure/issues/2774)
- [ ] [Plugin audit](https://github.com/adoptium/infrastructure/issues/3214)
- [ ] [Improve management of jenkins "jobs" disk usage](https://github.com/adoptium/infrastructure/issues/3285)
- [ ] [Utilise job restrictions plugin to improve build/test isolation.](https://github.com/adoptium/infrastructure/issues/3379)

**Comment by sxa** [comment]
You can run this over the logs to produce a summary of each type of entry failure from the log issues above (Number at the start of each line in the output is the issue number):
[jenkinslog-process.sh.txt](https://github.com/adoptium/infrastructure/files/14904870/jenkinslog-process.sh.txt)
