### ISSUE TITLE
EPIC: Upgrade Remaining Jenkins Agents To Java 17 from Java 11

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3741]
The next LTS version of Jenkins will require a minimum of JAVA 17 to run agents..

[https://www.jenkins.io/blog/2024/06/11/require-java-17/](https://www.jenkins.io/blog/2024/06/11/require-java-17/)

MOST of the current jenkins infrastructure runs on Java 17 or later however there are a number of machines ( see the table below ) that require updates..

There are 3 main tranches of agent upgrade that needs to be considered:

*   [ ] #3742 The Solaris agents will need an extensive solution ( see this 2nd Epic ) 
*   [x] #3743 The Eclipse Codesign Machine Requires A Java Upgrade performed by EF Infra
*    [x]  #3744 Update JDK11 nodes to JDK17

**Comment by sxa** [comment]
@steelhead31 Based on https://github.com/adoptium/infrastructure/issues/3925#issuecomment-2805507098 do you think this can now be closed? Looks like we've remediated all the ones that are going to be remediated ;-)

**Comment by steelhead31** [comment]
Yes, im happy we've done everything we need to :)
